resolver: lts-23.19
packages:
- conformance
- conformance-gen

# These are duplicated in nix/overlay.nix
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- timeout-0.1.1@sha256:56c1d3321d7139d1f7ebf04d46c95d3a3f1c8c9e0f15666ae3ccd6bae6204b6e,1427

system-ghc: true
nix:
  enable: false
with-hpack: hpack
