name: conformance-gen
version: 0.0.0.0

license: MIT
maintainer: Tom Sydney Kerckhove <syd@cs-syd.eu>
description: Testutils for conformance

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - conformance
  - sydtest


tests:
  conformance-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conformance
    - genvalidity-sydtest
    - sydtest
